# Generated by Django 4.2.1 on 2023-06-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, verbose_name="用户名")),
                ("content", models.TextField(verbose_name="评论内容")),
                ("comment_time", models.DateTimeField(auto_now_add=True)),
                ("like_num", models.IntegerField(default=0, verbose_name="点赞数")),
                ("is_like", models.IntegerField(default=0, verbose_name="是否已点赞")),
                ("reply_id", models.IntegerField(default=0, verbose_name="回复编号")),
                (
                    "reply_username",
                    models.CharField(
                        default="null", max_length=64, verbose_name="回复用户名"
                    ),
                ),
                (
                    "reply_userid",
                    models.IntegerField(default=0, verbose_name="回复评论用户id"),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="所属用户号")),
                ("root_id", models.IntegerField(default=0, verbose_name="根评论id")),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论列表",
                "db_table": "comment",
                "ordering": ["-comment_time"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=64, verbose_name="标签集合")),
                ("count", models.IntegerField(default=0, verbose_name="选用此标签的视频数量")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserToComment_like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="主体")),
                ("comment_id", models.IntegerField(default=0, verbose_name="点赞的评论")),
                ("root_id", models.IntegerField(default=0, verbose_name="点赞的根评论")),
            ],
        ),
        migrations.CreateModel(
            name="UserToFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="主体")),
                ("follow_id", models.IntegerField(default=0, verbose_name="关注的up主")),
            ],
        ),
        migrations.CreateModel(
            name="UserToHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="用户id")),
                ("video_id", models.IntegerField(default=0, verbose_name="看过的视频id")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="标题")),
                ("description", models.TextField(verbose_name="视频简介")),
                (
                    "video",
                    models.FileField(default="", upload_to="", verbose_name="视频"),
                ),
                (
                    "avatar",
                    models.FileField(default="", upload_to="", verbose_name="封面"),
                ),
                (
                    "avatar_path",
                    models.CharField(default="", max_length=256, verbose_name="封面路径"),
                ),
                (
                    "video_path",
                    models.CharField(default="", max_length=256, verbose_name="视频路径"),
                ),
                ("like_num", models.IntegerField(verbose_name="点赞数")),
                ("view_num", models.IntegerField(default=0, verbose_name="浏览量")),
                ("collect_num", models.IntegerField(default=0, verbose_name="收藏数")),
                (
                    "zone",
                    models.CharField(default="", max_length=32, verbose_name="专区"),
                ),
                (
                    "tag1",
                    models.CharField(default="", max_length=32, verbose_name="标签1"),
                ),
                (
                    "tag2",
                    models.CharField(default="", max_length=32, verbose_name="标签2"),
                ),
                (
                    "tag3",
                    models.CharField(default="", max_length=32, verbose_name="标签3"),
                ),
                (
                    "tag4",
                    models.CharField(default="", max_length=32, verbose_name="标签4"),
                ),
                (
                    "tag5",
                    models.CharField(default="", max_length=32, verbose_name="标签5"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("isAudit", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频",
                "verbose_name_plural": "视频列表",
                "db_table": "video",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Video_like_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="用户id")),
                ("video_id", models.IntegerField(default=0, verbose_name="点赞的视频id")),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(max_length=64, verbose_name="分区")),
            ],
        ),
        migrations.CreateModel(
            name="VideoComplain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                ("description", models.TextField(verbose_name="描述")),
                ("user_id", models.IntegerField(default=0, verbose_name="投诉人员编号")),
                ("verify_result", models.IntegerField(default=0, verbose_name="投诉结果")),
                (
                    "video",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.video",
                        verbose_name="所属视频",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comment", "New Comment"),
                            ("like", "New Like"),
                            ("follow", "New Follower"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.video"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.video",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.video",
                verbose_name="所属视频",
            ),
        ),
    ]
