# Generated by Django 4.2.1 on 2023-06-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToFan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="主体")),
                ("fan_id", models.IntegerField(default=0, verbose_name="粉丝")),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "网站用户", "verbose_name_plural": "网站用户列表"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(default=-1, upload_to="", verbose_name="用户头像"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(default="", max_length=128, verbose_name="用户头像路径"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.CharField(default="", max_length=32, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="collect_num",
            field=models.IntegerField(default=0, verbose_name="收获的收藏数"),
        ),
        migrations.AddField(
            model_name="user",
            name="complain_time",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="投诉时间"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=-1, verbose_name="创建时间"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="fan_num",
            field=models.IntegerField(default=0, verbose_name="粉丝数"),
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_num",
            field=models.IntegerField(default=0, verbose_name="收藏夹数"),
        ),
        migrations.AddField(
            model_name="user",
            name="follow_num",
            field=models.IntegerField(default=0, verbose_name="关注数"),
        ),
        migrations.AddField(
            model_name="user",
            name="isActive",
            field=models.BooleanField(default=False, verbose_name="是否有效"),
        ),
        migrations.AddField(
            model_name="user",
            name="isSuperAdmin",
            field=models.BooleanField(default=False, verbose_name="是否为超级管理员"),
        ),
        migrations.AddField(
            model_name="user",
            name="like_num",
            field=models.IntegerField(default=0, verbose_name="收获的点赞数"),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(default="中国大陆", max_length=32, verbose_name="所在地"),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="", max_length=30, verbose_name="昵称"),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(default="", max_length=12, verbose_name="性别"),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.CharField(default="", max_length=256, verbose_name="个人签名"),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=-1, max_length=30, verbose_name="用户名"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="video_num",
            field=models.IntegerField(default=0, verbose_name="视频数"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=32, verbose_name="密码"),
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
