# Generated by Django 4.2.2 on 2023-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="like_num",
            field=models.IntegerField(default=0, verbose_name="点赞数"),
        ),
    ]
